# Generated by Django 3.2.3 on 2024-01-01 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliche_builders', '0001_initial'),
        ('cliche_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicheScript',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('modified_time',
                 models.DateTimeField(
                     auto_now=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True)),
                ('name',
                 models.CharField(
                     max_length=255)),
                ('description',
                 models.TextField(
                     blank=True)),
                ('parameters',
                 models.JSONField(
                     default=dict)),
                ('code',
                 models.TextField()),
                ('app',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='scripts',
                     to='cliche_apps.clicheapp')),
                ('target',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='scripts',
                     to='cliche_builders.clichebuildtarget')),
            ],
            options={
                'unique_together': {
                    (
                        'target',
                        'app',
                        'name')},
            },
        ),
    ]
