# Generated by Django 3.2.3 on 2024-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliche_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clichescript',
            name='requirements',
            field=models.JSONField(default=dict),
        ),
    ]
