# Generated by Django 3.2.3 on 2024-01-06 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliche_apps', '0001_initial'),
        ('cliche_scripts', '0002_clichescript_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clichescript',
            name='app',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='scripts',
                to='cliche_apps.clicheapp'),
        ),
    ]
