# Generated by Django 3.2.3 on 2024-02-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliche_scripts', '0003_alter_clichescript_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clichescript',
            old_name='requirements',
            new_name='imports',
        ),
    ]
