# Generated by Django 3.2.3 on 2023-11-30 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClicheBuildTarget',
            fields=[
                ('name', models.CharField(
                    max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(
                    blank=True, default='')),
                ('requirements', models.JSONField(default=dict)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClicheBuilder',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(
                    auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('settings', models.JSONField(default=dict)),
                ('requirements', models.JSONField(default=dict)),
                ('directory', models.CharField(
                    blank=True, default='', max_length=255)),
                ('code_start', models.TextField(blank=True, default='')),
                ('code_finish', models.TextField(blank=True, default='')),
                ('target', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='builders',
                    to='cliche_builders.clichebuildtarget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
