# Generated by Django 3.2.3 on 2024-01-01 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliche_scripts', '0001_initial'),
        ('cliche_apps', '0001_initial'),
        ('cliche_models', '0001_initial'),
        ('cliche_schemas', '0002_auto_20231207_1217'),
        ('cliche_builders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicheView',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(
                    auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, max_length=511)),
                ('app', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='views', to='cliche_apps.clicheapp')),
            ],
            options={
                'unique_together': {('app', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClicheViewMethod',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(
                    auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('type', models.CharField(choices=[
                    ('GET', 'Get Method'),
                    ('POST', 'Post Method'),
                    ('PUT', 'Put Method'),
                    ('PATCH', 'Patch Method'),
                    ('DELETE', 'Delete Method'),
                    ('OPTION', 'Option Method')
                ], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('filter_schema', models.ForeignKey(
                    db_constraint=False, default=None, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='cliche_schemas.clicheschema')),
                ('input_schema', models.ForeignKey(
                    db_constraint=False, default=None, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='cliche_schemas.clicheschema')),
                ('model', models.ForeignKey(
                    db_constraint=False, default=None, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='cliche_models.clichemodel')),
                ('output_schema', models.ForeignKey(
                    db_constraint=False, default=None, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+', to='cliche_schemas.clicheschema')),
                ('view', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='methods', to='cliche_views.clicheview')),
            ],
            options={
                'unique_together': {('view', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ClicheViewMethodScript',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('modified_time', models.DateTimeField(
                    auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('method', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scripts',
                    to='cliche_views.clicheviewmethod')),
                ('script', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+',
                    to='cliche_scripts.clichescript')),
                ('target', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+',
                    to='cliche_builders.clichebuildtarget')),
            ],
            options={
                'unique_together': {('method', 'target')},
            },
        ),
    ]
